version: '3'

services:
  app1:
    build:
      context: ./app1
    container_name: my-app1
    networks:
      app_network:
        ipv4_address: 172.168.0.2  # Specify the static IP address for app1
    ports:
      - "3001:80"

  app2:
    build:
      context: ./app2
    container_name: my-app2
    networks:
      app_network:
        ipv4_address: 172.168.0.3  # Specify the static IP address for app2
    ports:
      - "3002:80"

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.168.0.0/16


